credentials:
  usernames:
    # Usuario con rol "admin" y área "PRE"
    mcalvino:
      first_name: "M"
      last_name: "Calvino"
      email: "[email protected]"
      password: "$2b$12$XXXXXXXXXXXXX"
      role: "admin"
      area: "PRE"

    # Usuario con rol "editor" y área "VPO"
    ajustinianon:
      first_name: "A"
      last_name: "Justinianon"
      email: "[email protected]"
      password: "$2b$12$YYYYYYYYYYYYY"
      role: "editor"
      area: "VPO"

    # Usuario con rol "viewer" y área "VPF"
    vgonzales:
      first_name: "V"
      last_name: "Gonzales"
      email: "[email protected]"
      password: "$2b$12$ZZZZZZZZZZZZZ"
      role: "viewer"
      area: "VPF"

    # Otro editor, área "VPE"
    vmoreira:
      first_name: "V"
      last_name: "Moreira"
      email: "[email protected]"
      password: "$2b$12$WWWWWWWWWWWWW"
      role: "editor"
      area: "VPE"

cookie:
  name: "mi_cookie_auth"
  key: "clave_secreta_unica"
  expiry_days: 60

preauthorized:
  emails: []
